<?php

return [
    'version' => '2.1.6',
    'sections' => [
        'overview' => 'Overview',
        'feature-reference' => 'Complete feature reference',
        'architecture' => 'How ModernCommerce works',
        'requirements' => 'Requirements',
        'installation' => 'Installation',
        'upgrading' => 'Upgrade & release compatibility',
        'quick-start' => 'Quick start',
        'roles-and-permissions' => 'Roles & permissions',
        'products-and-pricing' => 'Products & pricing',
        'course-merchandising' => 'Course merchandising',
        'bundles-and-programs' => 'Bundles & programs',
        'catalog-organization' => 'Categories, tags & discovery',
        'storefront' => 'Storefront & widgets',
        'branding-and-navigation' => 'Branding & Moodle navigation',
        'cart-and-checkout' => 'Cart & checkout',
        'payments' => 'Payments & gateways',
        'webhooks-and-payment-operations' => 'Webhooks & payment operations',
        'order-lifecycle' => 'Order lifecycle & fulfilment',
        'subscriptions' => 'Subscriptions',
        'coupons-and-keys' => 'Coupons & enrolment keys',
        'corporate-sales' => 'Corporate & B2B sales',
        'orders-invoices-refunds' => 'Orders, invoices & refunds',
        'learner-account' => 'Learner account & access',
        'customers-reviews-wishlists' => 'Customers, reviews & wishlists',
        'contacts-and-newsletter' => 'Contacts & newsletter',
        'notifications' => 'Notifications',
        'reports-and-analytics' => 'Reports & analytics',
        'admin-settings' => 'Admin settings reference',
        'scheduled-tasks' => 'Cron & scheduled tasks',
        'privacy-and-security' => 'Privacy & security',
        'admin-page-reference' => 'Admin page reference',
        'database-reference' => 'Database reference',
        'web-services-and-events' => 'Web services & events',
        'cli-and-maintenance' => 'CLI & maintenance',
        'localization' => 'Language & localization',
        'addons-and-extension' => 'Add-ons & extension points',
        'troubleshooting' => 'Troubleshooting',
        'faq' => 'FAQ',
    ],
];
